name: CI-Light

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    uses: PhoenixAscendDev/PXA-DevOps/GitHub-Actions/pxa-gha-ci-light.yml@main
    with:
      dotnet-version: '8.0.x'
