name: CI-Light

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  ci-light:
    uses: PhoenixAscendDev/PXA-DevOps/.github/workflows/pxa-gha-ci-light.yml@main
    with:
      dotnet-version: '8.0.x'
